name: lint
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Eslint
        run: npm run eslint . --ext .js
      - name: Prettier
        run: npm run prettier -c .
